[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tokens = "88BwGU74Yno9PQQVPZUQ3S93U6fGGjFKnpLfUxKDxKJf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dayanarp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
